#!/bin/bash

# Quick Production URL Setter
# Usage: ./scripts/set-prod-url.sh <api-url> [frontend-url]

set -e

if [ -z "$1" ]; then
    echo "❌ Error: API URL is required"
    echo "Usage: ./scripts/set-prod-url.sh <api-url> [frontend-url]"
    echo "Example: ./scripts/set-prod-url.sh https://api.example.com/api https://example.com"
    exit 1
fi

API_URL=$1
FRONTEND_URL=${2:-"https://example.com"}

echo "🔧 Setting production URLs..."
echo "   API URL: $API_URL"
echo "   Frontend URL: $FRONTEND_URL"

# Create or update .env.production.local
cat > .env.production.local << EOF
# Production Environment Configuration
# Generated by set-prod-url.sh

NODE_ENV=production

# API Configuration
NEXT_PUBLIC_API_BASE_URL=$API_URL
NEXT_PUBLIC_API_TIMEOUT=10000

# Application Configuration
NEXT_PUBLIC_APP_NAME=FullStack App
NEXT_PUBLIC_APP_URL=$FRONTEND_URL

# Authentication Configuration
NEXT_PUBLIC_TOKEN_REFRESH_THRESHOLD=300000
NEXT_PUBLIC_MAX_RETRY_ATTEMPTS=3
EOF

echo "✅ Production environment configured!"
echo "📝 File created: .env.production.local"
echo ""
echo "🚀 To use this configuration:"
echo "   npm run build"
echo "   npm run start"
echo ""
echo "   Or with Docker:"
echo "   docker compose up --build"

